name: cahbot
version: 1.0.0
description: Chat Against Humanity, the IRC party game.
dependencies:
  polymorphic_bot:
    git:
      url: git://github.com/PolymorphicBot/PolymorphicBot.git
      ref: cbe1db5a30d8fb2aa0afa960d68f564728314b6d
  http: '>=0.11.1+1 <0.12.0'
  irc: ">=2.0.4 <3.0.0"
